# Docker compose file that builds images and runs the containers needed for
# development. You need to have your MJKEY set in the environment.
#
# docker-compose \
#     -f ./docker/docker-compose.dev.gpu.yml \
#     build \
#         --build-arg MJKEY="$(cat ~/.mujoco/mjkey.txt)"

version: "2.4"
services:
  softlearning-dev-gpu:
    image: softlearning:${SOFTLEARNING_DEV_GPU_TAG}
    container_name: softlearning-dev-gpu
    runtime: nvidia
    build:
      context: ../.
      dockerfile: docker/Dockerfile.softlearning.base.gpu
      args:
        - MJKEY
    working_dir: /root/softlearning
    environment:
      - DISPLAY=:0
    ports:
      - "6006"  # Tensorboard
      - "5000"  # Viskit
      - "8888"  # Jupyter
    volumes:
       - ~/.aws:/root/.aws  # If using aws, e.g. for s3
       - ~/.config/gcloud:/root/.config/gcloud  # If using gcp, e.g. for gs
       - ~/.mujoco/mjkey.txt:/root/.mujoco/mjkey.txt  # mjkey.txt
       - ..:/root/softlearning
    command:
      - bash
    stdin_open: true
    tty: true
